ETAB
2218	01.03.2005	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2202	01.11.2003	PROD	HLIQ  HWEF    BHPT 10 
--********************--
204RTM	01.03.1995	PROD	HLIQ  HWEF    BHPT 10 
204RTM	01.03.2010	INJE	HWAT  HWEF    BHPT 500 
--********************--
192RTM	01.08.1994	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1806	01.11.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1805	01.10.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1803	01.06.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1802	01.03.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
157RTM	01.08.1994	PROD	HLIQ  HWEF    BHPT 10 
157RTM	01.10.2005	INJE	HWAT  HWEF    BHPT 500 
--********************--
2232	01.01.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2223B	01.07.2005	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2232	01.05.2011	PROD	HOIL  HWEF    BHPT 10 
--********************--
ENDE
